version: "3.8"

services:
    app:
        build:
            context: .
        container_name: app_dev
        ports:
        - 8008:80
        volumes:
        - ./app:/app
    redis:
        image: redis:latest
        container_name: redis_dev
        ports:
        - 6379:6379